In [1]:
import pandas as pd
df = pd.read_csv('datos_estudiantes.csv')
df

,Carrera Escogida,Escuela de Origen,Municipio,Estado,Sexo,Estado Civil,calFin,Paso
0,TSU EN GASTRONOMIA,CBTA # 5 (HUEJUTLA),HUEJUTLA DE REYES,YUCATAN,HOMBRE,VIUDO,8,1
1,TSU EN TECNOLOGIAS DE LA INFORMACION AREA DE S...,CENTRO DE ESTUDIOS DE BACHILLERATO MAESTRO MOI...,ATLAPEXCO,YUCATAN,HOMBRE,SOLTERO,9,1
2,TSU EN MECANICA AUTOMOTRIZ - TSU EN MECANICA I...,INSTITUTO TECNOLÓGICO DE EDUCACIÓN MEDIA SUPERIOR,ATLAPEXCO,YUCATAN,MUJER,VIUDO,10,1
3,TSU EN MECATRONICA Area Automatizacion,BACHILLERATO DEL ESTADO DE HIDALGO (PLANTEL YA...,TLANCHINOL,MEXICO,MUJER,DIVORCIADO,1,0
4,TSU EN GASTRONOMIA,CECYTE HUEJUTLA,HUEJUTLA DE REYES,PUEBLA,MUJER,DIVORCIADO,9,1
...,...,...,...,...,...,...,...,...
2995,TSU EN MECATRONICA Area Automatizacion,COBAEH ATLAPEXCO,HUEJUTLA DE REYES,JALISCO,MUJER,VIUDO,2,0
2996,TSU EN MECATRONICA Area Automatizacion,CECYTEH PLANTEL POXINDEJE,ATLAPEXCO,JALISCO,HOMBRE,SOLTERO,6,0
2997,TSU EN AGROBIOTECNOLOGIA,CECYTEH PLANTEL PACHUCA,TLANCHINOL,MEXICO,HOMBRE,VIUDO,10,1
2998,TSU EN CONSTRUCCION,CECYTEH PLANTEL POXINDEJE,YAHUALICA,JALISCO,MUJER,VIUDO,10,1
2999,TSU EN GASTRONOMIA,COBAEH HUEJUTLA,TLANCHINOL,MEXICO,HOMBRE,DIVORCIADO,6,0

In [2]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3000 entries, 0 to 2999
Data columns (total 8 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Carrera Escogida   3000 non-null   object
 1   Escuela de Origen  3000 non-null   object
 2   Municipio          3000 non-null   object
 3   Estado             3000 non-null   object
 4   Sexo               3000 non-null   object
 5   Estado Civil       3000 non-null   object
 6   calFin             3000 non-null   int64
 7   Paso               3000 non-null   int64
dtypes: int64(2), object(6)
memory usage: 187.6+ KB

In [3]:
x = df.drop(['Paso'], axis=1)
x.head(4)

,Carrera Escogida,Escuela de Origen,Municipio,Estado,Sexo,Estado Civil,calFin
0,TSU EN GASTRONOMIA,CBTA # 5 (HUEJUTLA),HUEJUTLA DE REYES,YUCATAN,HOMBRE,VIUDO,8
1,TSU EN TECNOLOGIAS DE LA INFORMACION AREA DE S...,CENTRO DE ESTUDIOS DE BACHILLERATO MAESTRO MOI...,ATLAPEXCO,YUCATAN,HOMBRE,SOLTERO,9
2,TSU EN MECANICA AUTOMOTRIZ - TSU EN MECANICA I...,INSTITUTO TECNOLÓGICO DE EDUCACIÓN MEDIA SUPERIOR,ATLAPEXCO,YUCATAN,MUJER,VIUDO,10
3,TSU EN MECATRONICA Area Automatizacion,BACHILLERATO DEL ESTADO DE HIDALGO (PLANTEL YA...,TLANCHINOL,MEXICO,MUJER,DIVORCIADO,1

In [4]:
y = df['Paso']
y.head(20)

0     1
1     1
2     1
3     0
4     1
5     1
6     1
7     1
8     1
9     1
10    1
11    1
12    0
13    1
14    1
15    1
16    1
17    1
18    1
19    0
Name: Paso, dtype: int64

# convertir categorico a numerico

In [5]:
#Letra a numero
from sklearn.preprocessing import OrdinalEncoder
encoder = OrdinalEncoder(handle_unknown='use_encoded_value', unknown_value=-1)
categorical_columns = ['Carrera Escogida', 'Escuela de Origen',
                       'Municipio', 'Estado', 'Sexo', 'Estado Civil','calFin']
x[categorical_columns] = encoder.fit_transform(x[categorical_columns])
x

,Carrera Escogida,Escuela de Origen,Municipio,Estado,Sexo,Estado Civil,calFin
0,4.0,1.0,1.0,4.0,0.0,3.0,8.0
1,9.0,8.0,0.0,4.0,0.0,2.0,9.0
2,5.0,17.0,0.0,4.0,1.0,3.0,10.0
3,6.0,0.0,2.0,2.0,1.0,1.0,1.0
4,4.0,3.0,1.0,3.0,1.0,1.0,9.0
...,...,...,...,...,...,...,...
2995,6.0,9.0,1.0,1.0,1.0,3.0,2.0
2996,6.0,5.0,0.0,1.0,0.0,2.0,6.0
2997,0.0,4.0,2.0,2.0,0.0,3.0,10.0
2998,1.0,5.0,3.0,1.0,1.0,3.0,10.0
2999,4.0,10.0,2.0,2.0,0.0,1.0,6.0

In [6]:
x.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3000 entries, 0 to 2999
Data columns (total 7 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Carrera Escogida   3000 non-null   float64
 1   Escuela de Origen  3000 non-null   float64
 2   Municipio          3000 non-null   float64
 3   Estado             3000 non-null   float64
 4   Sexo               3000 non-null   float64
 5   Estado Civil       3000 non-null   float64
 6   calFin             3000 non-null   float64
dtypes: float64(7)
memory usage: 164.2 KB

# se escalan los valores

In [7]:
#escalar
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scalerX = scaler.fit_transform(x)
scaler_titanic = pd.DataFrame(scalerX, columns=x.columns)
scaler_titanic.head(20)

,Carrera Escogida,Escuela de Origen,Municipio,Estado,Sexo,Estado Civil,calFin
0,-0.168683,-1.469455,-0.425959,1.441036,-1.031840,1.337439,0.209912
1,1.564358,-0.132140,-1.320831,1.441036,-1.031840,0.446802,0.557065
2,0.177925,1.587266,-1.320831,1.441036,0.969143,1.337439,0.904218
3,0.524533,-1.660500,0.468913,0.015679,0.969143,-0.443834,-2.220159
4,-0.168683,-1.087365,-0.425959,0.728358,0.969143,-0.443834,0.557065
5,-0.861899,0.632041,-0.425959,-0.697000,-1.031840,-1.334470,0.904218
6,1.217749,-0.514230,-1.320831,-0.697000,-1.031840,-1.334470,0.209912
7,-0.168683,-1.469455,1.363785,0.015679,-1.031840,-1.334470,0.557065
8,0.177925,0.440996,0.468913,-0.697000,0.969143,-1.334470,0.557065
9,0.524533,0.058906,0.468913,1.441036,-1.031840,-0.443834,0.904218
10,1.564358,-1.087365,-1.320831,0.728358,-1.031840,-1.334470,0.557065
11,0.177925,-1.087365,-0.425959,-0.697000,-1.031840,1.337439,0.557065
12,0.177925,0.440996,-1.320831,-0.697000,0.969143,0.446802,-0.484394
13,1.217749,1.014131,-1.320831,-1.409678,0.969143,-0.443834,0.209912
14,0.871141,-0.514230,-1.320831,-1.409678,-1.031840,-1.334470,0.904218
15,0.524533,-0.705275,-1.320831,-1.409678,0.969143,-0.443834,0.557065
16,-0.515291,-0.132140,1.363785,0.728358,-1.031840,-1.334470,0.557065
17,0.177925,1.205176,1.363785,1.441036,-1.031840,-0.443834,0.904218
18,0.871141,-1.660500,-0.425959,1.441036,0.969143,-1.334470,0.209912
19,-0.515291,0.249951,-1.320831,1.441036,0.969143,0.446802,-1.178700

# seleccion de caracteristicas

In [8]:
from sklearn.feature_selection import RFE
from sklearn.linear_model import LogisticRegression


#Crear modelo 
modelo = LogisticRegression(solver='lbfgs', max_iter=5000) # uaumentar maximo de iter 5000 por 1000

rfe = RFE(estimator=modelo, n_features_to_select=7, step=1)
rfe = rfe.fit(scaler_titanic, y)

for feature, selected in zip(scaler_titanic.columns, rfe.support_):
    print(f'{feature}: {selected}')

# Mostrar la clasificación de las características
print('Ranking de características:', rfe.ranking_)
# Mostrar las características seleccionadas
print('Características seleccionadas:', rfe.support_)

Carrera Escogida: True
Escuela de Origen: True
Municipio: True
Estado: True
Sexo: True
Estado Civil: True
calFin: True
Ranking de características: [1 1 1 1 1 1 1]
Características seleccionadas: [ True  True  True  True  True  True  True]

In [9]:
x_selected = scaler_titanic[scaler_titanic.columns[rfe.support_]]
x_selected.head(5)

,Carrera Escogida,Escuela de Origen,Municipio,Estado,Sexo,Estado Civil,calFin
0,-0.168683,-1.469455,-0.425959,1.441036,-1.031840,1.337439,0.209912
1,1.564358,-0.132140,-1.320831,1.441036,-1.031840,0.446802,0.557065
2,0.177925,1.587266,-1.320831,1.441036,0.969143,1.337439,0.904218
3,0.524533,-1.660500,0.468913,0.015679,0.969143,-0.443834,-2.220159
4,-0.168683,-1.087365,-0.425959,0.728358,0.969143,-0.443834,0.557065

In [10]:
x_selected.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3000 entries, 0 to 2999
Data columns (total 7 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Carrera Escogida   3000 non-null   float64
 1   Escuela de Origen  3000 non-null   float64
 2   Municipio          3000 non-null   float64
 3   Estado             3000 non-null   float64
 4   Sexo               3000 non-null   float64
 5   Estado Civil       3000 non-null   float64
 6   calFin             3000 non-null   float64
dtypes: float64(7)
memory usage: 164.2 KB

## modelo Random Forest

In [11]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import cross_val_score
rf = RandomForestClassifier(n_estimators=1000, random_state=42)

svm_scores = cross_val_score(rf, x_selected, y, cv=5, scoring='accuracy')
svm_scores.mean()

1.0

In [12]:
rf_model = RandomForestClassifier(n_estimators=1000, random_state=42)
rf_model.fit(x_selected, y)

RandomForestClassifier(n_estimators=1000, random_state=42)

In [13]:
svm_scoress = cross_val_score(rf_model, x_selected, y, cv=5, scoring='accuracy')
svm_scoress.mean()

1.0

In [14]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(x_selected, y, test_size=0.2, random_state=42)

# Entrenar el modelo Random Forest

svm_scoress = cross_val_score(rf_model, X_test, y_test, cv=5, scoring='accuracy')
svm_scoress.mean()

1.0

In [15]:
#           -0.168683	-1.469455	-0.425959	1.441036	-1.031840	1.337439	0.916079     ===>paso
#           0.524533	-1.660500	0.468913	0.015679	0.969143	-0.443834	-1.799235   ===> no paso
#12	        0.177925	0.440996	-1.320831	-0.697000	0.969143	0.446802	-2.138650 ===> no paso
#            -0.168683	-1.087365	-0.425959	0.728358	0.969143	-0.443834	0.237251   ===>paso
new_data = pd.DataFrame({
    'Carrera Escogida': [-0.168683],
    'Escuela de Origen': [-1.087365],
    'Municipio': [-0.425959],
    'Estado': [0.728358],  
    'Sexo': [0.969143],
    'Estado Civil': [-0.443834],
    'calFin': [0.237251]
   
})
prediction = rf_model.predict(new_data)
print(prediction)
print(f'Predicción: {"Pasó" if prediction[0] == 1 else "No Pasó"}')

[1]
Predicción: Pasó

In [16]:
# generar los 4 modelo de prediccion

In [17]:
import joblib
joblib.dump(encoder, 'modelo_ordinalEncoder.pkl')

['modelo_ordinalEncoder.pkl']

In [18]:
joblib.dump(scaler, 'modelo_Scaler.pkl')

['modelo_Scaler.pkl']

In [19]:
joblib.dump(rf_model, 'modelo_RandomForest.pkl')

['modelo_RandomForest.pkl']

In [21]:
df = df['Sexo']
df.head(1)

KeyError: 'Sexo'